CC=/opt/SUNWspro/bin/cc
AR=ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
CFLAGS=-O -I/usr/openwin/include -I/opt/SUNWmotif/include -DUSE_DIRENT
LIBS= -L/usr/openwin/lib -L/opt/SUNWmotif/lib -lm -Bstatic -lXm \
	-Bdynamic -lXt -lX11 -lgen -R /usr/openwin/lib

include Makefile.common
