$ !
$ ! VMS procedure to compile and link modules for utilities directory
$ !
$ ! SCCS ID: @(#)comutil.com	1.1     8/13/93
$ SET NOVERIFY
$ ON ERROR THEN EXIT
$ COMPILE := CC
$ SET VERIFY
$ COMPILE DIALOGF.C
$ COMPILE FILEUTILS.C
$ COMPILE GETFILES.c
$ COMPILE MISC.C  
$ COMPILE PREFFILE.C
$ COMPILE PRINTUTILS.C
$ COMPILE FONTSEL.C
$ LIBR/CREATE/OBJ LIBUTIL DIALOGF, FILEUTILS, GETFILES, MISC, -
	PRINTUTILS, PREFFILE, FONTSEL
$ COMPILE VMSUTILS.C
$ LIBR/CREATE/OBJ VMSUTILS VMSUTILS
